---
title: "WOEPS"
output: 
  html_document:
    toc: false  
    includes:
      in_header: header.html
    self_contained: false
---


```{css, echo=FALSE}
body, html {
  margin: 0;
  padding: 0;
  overflow-x: hidden;  /* Prevent horizontal scroll */
  background-color: #FDEDEC !important;
}

.navbar {
  background: url('https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Strasbourg_Ponts_couverts_au_coucher_du_soleil.jpg/2560px-Strasbourg_Ponts_couverts_au_coucher_du_soleil.jpg') no-repeat top center;
  background-size: cover;
  display: flex;            /* Enable flexbox for navbar */
  justify-content: center;  /* Center horizontally */
  align-items: center;      /* Center vertically */
  height: 300px;            /* Adjust the height as needed for your content */
  position: relative;       /* Allow it to scroll with the page */
  width: 100%;              /* Ensure it spans the full width of its parent */
  z-index: 1000;            /* Ensure it is above other content like the TOC */
  box-sizing: border-box;   /* Include padding and border in element's width/height */
  top: 0;                   /* Ensure it is at the very top of its container */
}

.navbar-brand {
  font-weight: bold;  
  line-height: 1.5;   
  font-size: 25px;
  color: #FDEDEC !important; /* Text color set to white */
  text-align: center;
  flex: none;
  text-shadow: -1.5px -1.5px 0 #000, 1.5px -1.5px 0 #000, -1.5px 1.5px 0 #000, 1.5px 1.5px 0 #000;
}

#TOC {
    color: #230556;               /* Dark purple color for the TOC text */
    background-color: #FDEDEC !important; /* Light purple background for the TOC */
    width: 50%;                   /* Set a width for the TOC */
    padding: 10px;                /* Add padding to the TOC */
    border: 1px solid #ccc;       /* Border around the TOC */
    margin: 20px auto;            /* Center the TOC using auto margins */
    text-align: left;             /* Align the text to the left inside the TOC */
    border-radius: 10px;          /* Rounded corners for the TOC */
}

#TOC ul {
    padding-left: 0;              /* Remove default padding from the list */
    margin: 0;                    /* Remove default margins to clean up the layout */
    background-color: #FDEDEC !important; /* Ensure background consistency */
}

#TOC li {
    list-style-type: none;        /* Remove bullet points */
    padding: 0px 0;               /* Reduce padding between items for closer spacing */
    margin-left: 0;               /* Remove left margin */
    font-size: 16px;              /* Set a readable font size */
}

#TOC a {
    color: #C19A8E;               /* Dark purple color for the TOC text */
    text-decoration: none;        /* Remove underlines from links */
    background-color: #FDEDEC;    /* Match the background to the TOC */
    display: block;               /* Make links fill the li element for easier clicking */
    padding: 0px 0;               /* Padding to make links taller, easier to click, reduced vertical padding for tighter layout */
}

#TOC a:hover {
    color: #FFAB91;               /* Light pastel coral for the hover text */
    background-color: #FAE5E3;    /* Very light pink for the hover background */
}

#applyButton {
    background-color: #FFAB91;  /* Light pastel coral */
    border: none; 
    color: #FDEDEC;  /* Light peach/pink */
    padding: 15px 32px; 
    text-align: center; 
    display: inline-block; 
    font-size: 16px; 
    margin: 4px 2px; 
    cursor: pointer; 
    border-radius: 10px; 
    transition: background-color 0.3s, color 0.3s;  /* Smooth transition for hover effects */
}

#applyButton:hover {
    background-color: #FAE5E3; /* Very light pink for the hover background */
    color: #FFAB91;            /* Light pastel coral for the hover text */
}

/* Style for all links */
a {
    color: #C19A8E;               /* Soft terracotta */
    text-decoration: none;        /* Remove underline */
    transition: color 0.3s, background-color 0.3s; /* Smooth transition for hover effects */
}

/* Hover effect for all links */
a:hover {
    color: #FFAB91;               /* Light pastel coral */
    background-color: #FAE5E3;    /* Very light pink */
}

h1.title {
  display: none;
}
table {
    width: 100%; /* Important for overall table width */
    border-collapse: collapse;
    margin: 0;
}

th,
td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
}

th:first-child,
td:first-child {
    width: 40px; /* Adjust this value as needed */
}

th {
    background-color: #FAE5E3;
}

/* Media query for larger screens */
@media (min-width: 768px) {
    table {
        margin: 20px auto;
        max-width: 80%;
    }
}
```

<style>
/* Center level 1 headings and change color */
h1 {
  text-align: center;
  color: #A76D60; 
}

h2, h3, h4, h5, h6 {
  color: #A76D60; 
}
</style>


<br><br>

The **Bureau d'Économie Théorique et Appliquée (BETA)** and **University of Strasbourg** are organising the annual workshop “The Organisation, Economics and Policy of Scientific Research” at BETA's venue in Strasbourg.

<br><br>

<div style="text-align: center;">

**Date:** 3-4 April 2025

**Location:** Strasbourg, France

**Contact**: [woeps.contact@gmail.com](mailto:woeps.contact@gmail.com)

</div>



---


 <div style="text-align: center;">
 <a href="https://github.com/woeps-workshop/BETA-2025/raw/gh-page/files/woeps2025.pdf" style="text-decoration: none;">
     <button id="applyButton">
         Download Program in PDF
     </button>
 </a>
 </div>
##   2nd April 2025

|   Time   | Event                                                                                             |
|   :----- | :------------------------------------------------------------------------------------------------ |
|   20:00 | Informal Get-Together – Pre-Workshop Dinner (Location: Le Météor - 10 Rue du 22 Novembre, 67000 Strasbourg) |

##   Day 1

###   3rd April 2025

|   Time   | Event                                                                                                                            |
|   :----- | :------- |
|  08:30 – 08:55 | Registration and Welcome Coffee |
|  08:55 – 09:00 | Welcome Address                 |

###   Session 1: Gender Issues in Academia
 Chair: Catherine Beaudry

|   Time   | Paper                                                                                                                                                                                                                                       | Discussant           |
|   :----- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------- |
|   09:00 – 09:30 |   **Children and Careers in Swedish Academia** \
    Peter Holmström *(Lund University, Department of Economic History)* and Olof Ejermo *(Lund University, Department of Economic History)* |   Cornelia Lawson     |
|   09:30 – 10:00 |   **Connections in Academia: Collaboration and Gender** \
    Milan Makany *(Erasmus University Rotterdam )* |   Fabiana Vinsentin |
|   10:00 – 10:30 |   **From the Ivory Tower to Capitol Hill: Which Academics Get a Voice in Congress?** \
    Astrid Ulv Thomsen *(Copenhagen Business School)* and Yotam Sofer *(Copenhagen Business School)* |  Michael Rose    |

|   Time   | Event         |
|   :----- | :--- |
|   10:30 – 10:45 | \
Coffee Break |

###   Session 2: Mobility and International Collaboration
 Chair: Sotaro Shibayama

|   Time   | Paper                                                                                                                                                                                                                                                                     | Discussant          |
|   :----- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------ |
|   10:45 – 11:15 |   **Trump, Iran and Science** \
    Stefano Baruffaldi *(Politecnico di Milano)*, Carolin Formella *(Max Planck Institute for Innovation and Competition)* and Michael Rose *(Max Planck Institute for Innovation and Competition)* |   Catherine Beaudry |
|   11:15 – 11:45 |   **Navigating the Knowledge boundaries: The Impact of Collaborating with Internationally Mobile Researchers on Non-mobile Researchers' Knowledge exploration and creation** \
    Rodrigo Ito *(Maastricht University)*, Diego Chavarro *(Research Policy Solutions)*, Tommaso Ciarli *(United Nations University-MERIT)*, Robin Cowan *(University of Strasbourg and Maastricht University)* and Fabiana Visentin *(Maastricht University)* |   Aldo Geuna          |
|   11:45 – 12:15 |   **Immigrants or Emigrants, Which One is the Better Choice for Scientific Collaboration?** \
    Amirali Karimi *(Polytechnique Montréal)*, Catherine Beaudry *(Polytechnique Montréal)* and Vincent Larivière *(Université de Montréal)* |   Moritz Müller       |

|   Time   | Event                                                                                                 |
|   :----- | :---------------------------------------------------------------------------------------------------- |
|   12:15 – 14:00 |   **A Tribute to Richard 'Dick' Nelson**  -- Patrick Llerena *(University of Strasbourg)* et al.  \
\
Lunch Break ( Resto Le 32 ) |
|   14:00 – 15:15 |   **Keynote Speech** \
Jacques Mairesse *CREST (ENSAE, Paris), UNU-MERIT (Maastricht University), NBER*  |
| 15:15 – 15:30 | \
Coffee Break |

###   Session 3: Research Funding and Evaluation Mechanisms
 Chair: Cornelia Lawson

|   Time   | Paper                                                                                                                                                                                                                                                                             | Discussant          |
|   :----- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :------------------ |
|   15:30 – 16:00 |   **Addressing Conservatism in Funding Decisions via Enhanced Selection Mechanisms** \
    Thomas Feliciani *(Politecnico di Milano)*, Rikke Nørding Christensen *(Novo Nordisk Foundation)* and Chiara Franzoni *(Politecnico di Milano)* |   Nicolas Carayol   |
|   16:00 – 16:30 |   **Mitigating Negativity in Science Funding: The Role of Two-Step Procedures and Group Decision-Making** \
    Hanna Hottenrott *(Leibniz Centre for European Economic Research (ZEW))*, Lakshya Katariya *(KU Leuven)* and Cindy Lopes Bento *(KU Leuven)* |   Michele Pezzoni   |
|   16:30 – 17:00 |   **How to Pay for Scientific Research** \
    Daniele Checchi *(University of Milan)*, Gianni De Fraja *(University of Nottingham)*, Carmen Marchiori *(University of Brescia)*, Enrico Minelli *(University of Brescia)* and Stefano Verzillo *(European Commission, Joint Research Centre)* |   Reinhilde Veugelers |

|   Time   | Event                                                                                                                             |
|   :----- | :-------------------------------------------------------------------------------------------------------------------------------- |
|   20:00 | Conference Dinner (Location: Caveau Du Gurtlerhoft, Restaurant Gurtlerhoft, 13 Pl. de la Cathédrale, 67000 Strasbourg) |

##   Day 2

###   4th April 2024

###   Session 4: Knowledge Transfer and Collaborations
 Chair: Fabiana Visentin

|   Time   | Paper                                                                                                                                                                                                                                                                      | Discussant      |
|   :----- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :-------------- |
|   9:00 - 9:30 |   **Harnessing Academic Science for Corporate Technology: The Role of Interpersonal Networks and Brokers** \
    Sam Arts *(KU Leuven)*, Lee Fleming *(UC Berkeley)* and Elena Veretennik *(KU Leuven)* |   Julien Penin    |
|   9:30 - 10:00 |   **When one teaches, two learn: The bidirectional learning process supervisor-PhD student** \
    Pierre Boutros *(Université Côte d'Azur, CNRS, GREDEG)*, Michele Pezzoni *(Université Côte d'Azur, CNRS, GREDEG)*, Sotaro Shibayama *(Institute for Future Initiatives, The University of Tokyo)* and Fabiana Visentin *(UNU-MERIT, Maastricht University)* |   Guido Buenstorf  |
|   10:00 - 10:30 |   **Evolving Networks of Scientists and Engineers: Strategic Complementarities and Science Policy** \
    James Adams *(Rensselaer Polytechnic Institute and NBER)*, Ameya Hate *(Akamai Technologies)* and J. Roger Clemmons *(United HealthCare)* |   Robin Cowan      |



###   Session 5: Artificial Intelligence in Science
 Chair: Stefano Bianchini

|   Time   | Paper                                                                                                                                                                                                                                       | Discussant        |
|   :----- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :---------------- |
|   10:45 - 11:15 |   **Transformative Impact of HPC and AI on Science** \
    Fazliddin Shermatov *(University of Turin and Université Sorbonne Paris Nord)*, Stefano Bianchini *(University of Strasbourg)* and Aldo Geuna *(University of Turin)* |   Henry Sauerman   |
|   11:15 - 11:45 |   **Does Training in AI Affect PhD Students' Careers? Evidence From France** \
    Pierre Boutros *(Université Côte d'Azur)*, Eliana Diodati *(University of Torino, Collegio Carlo Alberto)*, Michele Pezzoni *(Université Côte d'Azur)* and Fabiana Visentin *(UNU-MERIT, Maastricht University)* |   Stijn Kelchtermans|
|   11:45 – 12:15 |   **Chat-PhD: The Role of LLM in Shaping the Research Practices and Productivity of Young Scholars** \
    Ivan Napoli *(Catholic University of Milan)*, Stefano Bianchini *(University of Strasbourg)*, Gabriele Pellegrino *(Catholic University of Milan)* and Pierre Pelletier *(University of Strasbourg)* |   Sotaro Shibayama |

|   Time   | Event         |
|   :----- | :-------------------------------------------------------------------------------------------------------------------------------- |
|   12:15 – 13:45 | \
Lunch Break |

###   Session 6: Interdisciplinarity and Scientific Impact
 Chair: Reinhilde Veugelers

|   Time   | Paper                                                                                                                                                                                                                                              | Discussant      |
|   :----- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :-------------- |
|   13:45 - 14:15 |   **Entangling the Impact of Methodological and Topic Interdisciplinarity on Scientific Performance in Economics** \
    Diletta Abbonato *(University of Milan-Bicocca)* and Marco Guerzoni *(University of Milan-Bicocca)* |   Nicola Meluso    |
|   14:15 – 14:45 |   **Specialization and Academic Career: Different Effects in Different Career Stages** \
    Jian Wang *(Lancaster University Leipzig)* and Sotaro Shibayama *(University of Tokyo)* |   Daniel Souza      |
|   14:45 – 15:15 |   **The Impact of Scientific Characteristics on Green Technologies: Exploring Novel and Interdisciplinary Knowledge** \
    Cornelia Lawson *(Manchester Institute of Innovation Research (MIOIR))*, Silvia Massini *(Alliance Manchester Business School)* and An Yu Chen *(Alliance Manchester Business School)* |   Fabio Montobio   |

|   Time   | Event         |
|   :----- | :-------------------------------------------------------------------------------------------------------------------------------- |
|   15:15 – 15:30 | \
Coffee Break |

###   Session 7: Selection Bias and Opportunity in Academic Careers
 Chair: Patrick Llerena

|   Time   | Paper                                                                                                                                                                                               | Discussant       |
|   :----- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :--------------- |
|   15:00 – 15:20 |   **The Chosen: Researcher Visas and Foreign PhD graduates' careers in France** \
    Andriy Romanyuk *(University of Bordeaux and Università degli Studi dell'Insubria)*, Alberto Corsini *(CSIC, Institute of Public Goods and Policies)* and Francesco Lissoni *(University of Bordeaux and Università Cattolica del Sacro Cuore)* |   Mary Fox           |
|   15:20 – 15:40 |   **Judging the Paper by Its Cover: Affiliation Bias in Conference Admissions** \
    Giacomo Gallegati *(Collegio Carlo Alberto, University of Turin, University Paris 1 Panthéon-Sorbonne)*, Luca Favero *(University of Essex)*, Agueda Solis Alonso *(Collegio Carlo Alberto, University of Turin)* and Enrique Carreras *(Collegio Carlo Alberto, University of Turin)* |   Jacques Mairesse |

|   Time   | Event   |
|   :----- | :------------------------------------------------------------------------------- |
|   16:10 | Farewell |

<br><br>

<br><br>

**Speaking Time**

Presenters have 20 minutes, discussants 5 minutes. 

---

<br><br>

# **Venue**

The workshop will take place at the **Bureau d'Economie Théorique et Appliquée**, located at **61 Avenue de la Forêt-Noire, 67000 Strasbourg**.


<div style="text-align: center;">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.4030502252085!2d7.773789400000001!3d48.5829811!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c8e3638cdc5b%3A0x2f20a0b00a7ed8cc!2sP%C3%B4le%20europ%C3%A9en%20de%20gestion%20et%20d&#39;%C3%A9conomie!5e0!3m2!1sfr!2sfr!4v1727433618548!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

---

<br><br>

# **Some Accommodation Options**

- LE 21ème (**)

  *Address*:21 rue du Fossé des Tanneurs 

  *Phone*:03 88 23 89 21 

  *Contact*: hotel21strasbourg.com 

- HOTEL ESPLANADE (**)

  *Address*: 1 boulevard Leblois 

  *Phone*: +33 3 88 61 38 95 

  *Contact*: info@hotel-esplanade.fr 

- HOTEL DES ARTS (**)

  *Address*: 10 Place du Marché aux Cochons-de-Lait

  *Phone*: 03 88 37 98 37 

  *Contact*: hotel-arts.com 

- APPART’HOTEL LES CITADINES Kléber Strasbourg (***)

  *Address*: 50-54 rue du Jeu des Enfants 

  *Phone*: +33 3 90 22 47 00 

  *Contact*: groupe@citadines.com 

- MAISON ROUGE (****)

  *Address*: 4 rue des Francs Bourgeois 

  *Phone*: +33 3 88 32 08 60 

  *Contact*: maison-rouge.com 



---

<br><br>

# **Scientific Committee**
- Cristiano Antonelli (Università di Torino)
- Catherine Beaudry (Polytechnique Montréal)
- Stefano Bianchini (Université de Strasbourg)
- Nicolas Carayol (Bordeaux School of Economics)
- Michele Cincera (Université Libre de Bruxelles)
- Aldo Geuna (Università di Torino)
- Hanna Hottenrott (TUM)
- Stijn Kelchtermans (KU Leuven)
- Cornelia Lawson (University of Manchester)
- Patrick Llerena (Université de Strasbourg)
- Jacques Mairesse (UNU-MERIT, Maastricht University)
- Fabio Montobbio (Università Cattolica del Sacro Cuore)
- Michele Pezzoni (Université Côte d'Azur)
- Henry Sauermann (ESMT Berlin)
- Sotaro Shibayama (University of Tokyo)
- Paula Stephan (Georgia State University; NBER)
- Valentina Tartari (Stockholm School of Economics)
- Reinhilde Veugelers (KU Leuven)
- Fabiana Visentin (UNU-MERIT, Maastricht University)
- John Walsh (Georgia Institute of Technology)

<br><br>

# **Local Organising Committee**
- Stefano Bianchini (Université de Strasbourg)
- Robin Cowan (Université de Strasbourg; UNU-MERIT, Maastricht University)
- Patrick Llerena (Université de Strasbourg)
- Pierre Pelletier (Université de Strasbourg)
- Julien Pénin (Université de Strasbourg)
- Sandrine Wolff (Université de Strasbourg)

---

<br><br>

contact us at: [woeps.contact@gmail.com](mailto:woeps.contact@gmail.com)
</div>

